-- ============================================
-- Create Appointments Tables Migration
-- ============================================

-- Create appointments table
CREATE TABLE IF NOT EXISTS "public"."appointments" (
    "id" bigint generated by default as identity not null,
    "patient_id" bigint not null,
    "appointment_date" date not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "duration_minutes" integer not null default 60,
    "appointment_type" text not null,
    "status" text not null default 'scheduled',
    "notes" text,
    "mini_notes" text,
    "full_notes" text,
    "pickup_instructions" text,
    "custom_fields" jsonb,
    "primary_staff_id" bigint,
    "driver_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

-- Create appointment_staff_assignments table (junction table for many-to-many)
CREATE TABLE IF NOT EXISTS "public"."appointment_staff_assignments" (
    "id" bigint generated by default as identity not null,
    "appointment_id" bigint not null,
    "staff_id" bigint not null,
    "role" text not null default 'other',
    "created_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id"),
    UNIQUE ("appointment_id", "staff_id", "role")
);

-- Enable RLS
ALTER TABLE "public"."appointments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."appointment_staff_assignments" ENABLE ROW LEVEL SECURITY;

-- Add foreign key constraints for appointments
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'appointments_patient_id_fkey'
    ) THEN
        ALTER TABLE "public"."appointments" 
        ADD CONSTRAINT "appointments_patient_id_fkey" 
        FOREIGN KEY (patient_id) 
        REFERENCES contacts(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'appointments_primary_staff_id_fkey'
    ) THEN
        ALTER TABLE "public"."appointments" 
        ADD CONSTRAINT "appointments_primary_staff_id_fkey" 
        FOREIGN KEY (primary_staff_id) 
        REFERENCES staff(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'appointments_driver_id_fkey'
    ) THEN
        ALTER TABLE "public"."appointments" 
        ADD CONSTRAINT "appointments_driver_id_fkey" 
        FOREIGN KEY (driver_id) 
        REFERENCES staff(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

-- Add foreign key constraints for appointment_staff_assignments
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'appointment_staff_assignments_appointment_id_fkey'
    ) THEN
        ALTER TABLE "public"."appointment_staff_assignments" 
        ADD CONSTRAINT "appointment_staff_assignments_appointment_id_fkey" 
        FOREIGN KEY (appointment_id) 
        REFERENCES appointments(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'appointment_staff_assignments_staff_id_fkey'
    ) THEN
        ALTER TABLE "public"."appointment_staff_assignments" 
        ADD CONSTRAINT "appointment_staff_assignments_staff_id_fkey" 
        FOREIGN KEY (staff_id) 
        REFERENCES staff(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

-- Create policies for appointments
CREATE POLICY "Enable read access for authenticated users"
ON "public"."appointments"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."appointments"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."appointments"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."appointments"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Create policies for appointment_staff_assignments
CREATE POLICY "Enable read access for authenticated users"
ON "public"."appointment_staff_assignments"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."appointment_staff_assignments"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."appointment_staff_assignments"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."appointment_staff_assignments"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."appointments" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."appointments" TO "service_role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."appointment_staff_assignments" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."appointment_staff_assignments" TO "service_role";

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS "appointments_patient_id_idx" ON "public"."appointments" ("patient_id");
CREATE INDEX IF NOT EXISTS "appointments_appointment_date_idx" ON "public"."appointments" ("appointment_date");
CREATE INDEX IF NOT EXISTS "appointments_start_time_idx" ON "public"."appointments" ("start_time");
CREATE INDEX IF NOT EXISTS "appointments_status_idx" ON "public"."appointments" ("status");
CREATE INDEX IF NOT EXISTS "appointments_appointment_type_idx" ON "public"."appointments" ("appointment_type");
CREATE INDEX IF NOT EXISTS "appointments_primary_staff_id_idx" ON "public"."appointments" ("primary_staff_id");
CREATE INDEX IF NOT EXISTS "appointments_driver_id_idx" ON "public"."appointments" ("driver_id");
CREATE INDEX IF NOT EXISTS "appointment_staff_assignments_appointment_id_idx" ON "public"."appointment_staff_assignments" ("appointment_id");
CREATE INDEX IF NOT EXISTS "appointment_staff_assignments_staff_id_idx" ON "public"."appointment_staff_assignments" ("staff_id");

-- Add check constraints for valid values
ALTER TABLE "public"."appointments" 
ADD CONSTRAINT "appointments_appointment_type_check" 
CHECK (appointment_type IN ('doctor_on_call', 'lab_test', 'teleconsultation', 'physiotherapy', 'caregiver', 'iv_therapy'));

ALTER TABLE "public"."appointments" 
ADD CONSTRAINT "appointments_status_check" 
CHECK (status IN ('scheduled', 'confirmed', 'completed', 'cancelled'));

ALTER TABLE "public"."appointment_staff_assignments" 
ADD CONSTRAINT "appointment_staff_assignments_role_check" 
CHECK (role IN ('primary', 'driver', 'other'));

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_appointments_updated_at BEFORE UPDATE ON "public"."appointments"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

