-- ============================================
-- B2C CRM Transformation Migration
-- ============================================

-- 1. Create services table
CREATE TABLE IF NOT EXISTS "public"."services" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;

-- 2. Insert default services (only if table is empty)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "public"."services" LIMIT 1) THEN
        INSERT INTO "public"."services" (name) VALUES 
          ('Doctor on Call'),
          ('Teleconsultation'),
          ('Physiotherapy'),
          ('Nurse on Call'),
          ('Blood Test'),
          ('IV Therapy'),
          ('Nanny'),
          ('Elderly Care');
    END IF;
END $$;

-- 3. Add columns to contacts (leads)
ALTER TABLE "public"."contacts" 
  ADD COLUMN IF NOT EXISTS "flat_villa_number" text,
  ADD COLUMN IF NOT EXISTS "building_street" text,
  ADD COLUMN IF NOT EXISTS "area" text,
  ADD COLUMN IF NOT EXISTS "google_maps_link" text,
  ADD COLUMN IF NOT EXISTS "phone_has_whatsapp" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "services_interested" bigint[];

-- 4. Add columns to companies (clients)
ALTER TABLE "public"."companies"
  ADD COLUMN IF NOT EXISTS "services" bigint[],
  ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'Active';

-- 5. Add lead_id to deals
ALTER TABLE "public"."deals"
  ADD COLUMN IF NOT EXISTS "lead_id" bigint;

-- Make company_id optional (if it's currently NOT NULL)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'deals' 
        AND column_name = 'company_id' 
        AND is_nullable = 'NO'
    ) THEN
        ALTER TABLE "public"."deals" ALTER COLUMN "company_id" DROP NOT NULL;
    END IF;
END $$;

-- Add foreign key constraint for lead_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'deals_lead_id_fkey'
    ) THEN
        ALTER TABLE "public"."deals" 
        ADD CONSTRAINT "deals_lead_id_fkey" 
        FOREIGN KEY (lead_id) 
        REFERENCES contacts(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

-- 6. Update views
DROP VIEW IF EXISTS "public"."contacts_summary";

CREATE VIEW "public"."contacts_summary"
AS
SELECT 
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.email_jsonb,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text as email_fts,
    co.phone_jsonb,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text as phone_fts,
    co.flat_villa_number,
    co.building_street,
    co.area,
    co.google_maps_link,
    co.phone_has_whatsapp,
    co.services_interested,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    c.name as company_name,
    count(DISTINCT t.id) as nb_tasks
FROM
    "public"."contacts" co
LEFT JOIN
    "public"."tasks" t ON co.id = t.contact_id
LEFT JOIN
    "public"."companies" c ON co.company_id = c.id
GROUP BY
    co.id, c.name;

DROP VIEW IF EXISTS "public"."companies_summary";

CREATE VIEW "public"."companies_summary"
    WITH (security_invoker=on)
AS
SELECT 
    c.*,
    count(DISTINCT t.id) as nb_tasks
FROM 
    "public"."companies" c
LEFT JOIN 
    "public"."tasks" t ON t.contact_id IN (
        SELECT id FROM "public"."contacts" WHERE company_id = c.id
    )
GROUP BY 
    c.id;

-- 7. Set up policies for services
DO $$
BEGIN
    -- Drop existing policies if they exist
    DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."services";
    DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "public"."services";
    DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."services";
    DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."services";
    
    -- Create new policies
    CREATE POLICY "Enable read access for authenticated users"
    ON "public"."services"
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);

    CREATE POLICY "Enable insert for authenticated users"
    ON "public"."services"
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

    CREATE POLICY "Enable update for authenticated users"
    ON "public"."services"
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING (true);

    CREATE POLICY "Enable delete for authenticated users"
    ON "public"."services"
    AS PERMISSIVE
    FOR DELETE
    TO authenticated
    USING (true);
END $$;

-- 8. Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."services" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."services" TO "service_role";

