-- Create staff table
create table "public"."staff" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text not null,
    "staff_type" text not null,
    "specialization" text,
    "phone" text not null,
    "email" text,
    "status" text not null default 'active'
);

-- Create primary key
alter table "public"."staff" add constraint "staff_pkey" primary key ("id");

-- Enable RLS
alter table "public"."staff" enable row level security;

-- Create policies for authenticated users
create policy "Enable read access for authenticated users"
    on "public"."staff"
    for select
    using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
    on "public"."staff"
    for insert
    with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
    on "public"."staff"
    for update
    using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
    on "public"."staff"
    for delete
    using (auth.role() = 'authenticated');

-- Create index for faster lookups
create index "staff_status_idx" on "public"."staff" ("status");
create index "staff_staff_type_idx" on "public"."staff" ("staff_type");


