-- ============================================
-- Create Quotes Table Migration
-- ============================================

-- Create quotes table
CREATE TABLE IF NOT EXISTS "public"."quotes" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint not null,
    "service_id" bigint,
    "description" text,
    "amount" numeric(10, 2) DEFAULT 0.00,
    "status" text DEFAULT 'Draft',
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "sales_id" bigint,
    PRIMARY KEY ("id")
);

ALTER TABLE "public"."quotes" ENABLE ROW LEVEL SECURITY;

-- Add foreign key constraints
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'quotes_contact_id_fkey'
    ) THEN
        ALTER TABLE "public"."quotes" 
        ADD CONSTRAINT "quotes_contact_id_fkey" 
        FOREIGN KEY (contact_id) 
        REFERENCES contacts(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'quotes_service_id_fkey'
    ) THEN
        ALTER TABLE "public"."quotes" 
        ADD CONSTRAINT "quotes_service_id_fkey" 
        FOREIGN KEY (service_id) 
        REFERENCES services(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'quotes_sales_id_fkey'
    ) THEN
        ALTER TABLE "public"."quotes" 
        ADD CONSTRAINT "quotes_sales_id_fkey" 
        FOREIGN KEY (sales_id) 
        REFERENCES sales(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

-- Create policies for quotes
CREATE POLICY "Enable read access for authenticated users"
ON "public"."quotes"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."quotes"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."quotes"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."quotes"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."quotes" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."quotes" TO "service_role";

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS "quotes_contact_id_idx" ON "public"."quotes" ("contact_id");
CREATE INDEX IF NOT EXISTS "quotes_service_id_idx" ON "public"."quotes" ("service_id");
CREATE INDEX IF NOT EXISTS "quotes_status_idx" ON "public"."quotes" ("status");






