-- ============================================
-- Create Activity Log Table for Deletion Events
-- ============================================

-- Create activity_log table to store deletion events
CREATE TABLE IF NOT EXISTS "public"."activity_log" (
    "id" bigint generated by default as identity not null,
    "type" text not null,
    "sales_id" bigint,
    "contact_id" bigint,
    "deal_id" bigint,
    "note_text" text,
    "quote_amount" numeric(10, 2),
    "quote_description" text,
    "task_text" text,
    "task_type" text,
    "date" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

ALTER TABLE "public"."activity_log" ENABLE ROW LEVEL SECURITY;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS "activity_log_type_idx" ON "public"."activity_log" ("type");
CREATE INDEX IF NOT EXISTS "activity_log_date_idx" ON "public"."activity_log" ("date");
CREATE INDEX IF NOT EXISTS "activity_log_contact_id_idx" ON "public"."activity_log" ("contact_id");
CREATE INDEX IF NOT EXISTS "activity_log_sales_id_idx" ON "public"."activity_log" ("sales_id");

-- Create policies for activity_log
CREATE POLICY "Enable read access for authenticated users"
ON "public"."activity_log"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."activity_log"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Grant permissions
GRANT SELECT, INSERT ON TABLE "public"."activity_log" TO "authenticated";
GRANT SELECT, INSERT ON TABLE "public"."activity_log" TO "service_role";





