-- ============================================
-- Create General Settings Table
-- ============================================
-- This table stores general application settings like office location

-- Create general_settings table
CREATE TABLE IF NOT EXISTS "public"."general_settings" (
    "id" bigint generated by default as identity not null,
    "setting_key" text not null,
    "setting_value" jsonb not null,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id"),
    UNIQUE ("setting_key")
);

-- Enable RLS
ALTER TABLE "public"."general_settings" ENABLE ROW LEVEL SECURITY;

-- Create policies for general_settings
CREATE POLICY "Enable read access for authenticated users"
ON "public"."general_settings"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."general_settings"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."general_settings"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."general_settings"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."general_settings" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."general_settings" TO "service_role";

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS "general_settings_setting_key_idx" ON "public"."general_settings" ("setting_key");

-- Add trigger to update updated_at timestamp
CREATE TRIGGER update_general_settings_updated_at BEFORE UPDATE ON "public"."general_settings"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default office location setting
INSERT INTO "public"."general_settings" (setting_key, setting_value, description)
VALUES (
    'office_location',
    '{"latitude": 25.2048, "longitude": 55.2708, "address": "Office, Dubai, UAE"}'::jsonb,
    'Office location coordinates and address for transport routing'
)
ON CONFLICT (setting_key) DO NOTHING;

