-- ============================================
-- Create Driver Trips Tables Migration
-- ============================================
-- This migration creates the driver_trips and trip_legs tables
-- for the Driver Assignment & Dispatch System

-- Create driver_trips table
CREATE TABLE IF NOT EXISTS "public"."driver_trips" (
    "id" bigint generated by default as identity not null,
    "driver_id" bigint not null,
    "trip_date" date not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "status" text not null default 'draft',
    "vehicle_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

-- Create trip_legs table
CREATE TABLE IF NOT EXISTS "public"."trip_legs" (
    "id" bigint generated by default as identity not null,
    "trip_id" bigint not null,
    "leg_type" text not null,
    "leg_order" integer not null,
    "staff_id" bigint,
    "appointment_id" bigint,
    "location_type" text not null,
    "location_id" bigint,
    "planned_arrival_time" timestamp with time zone not null,
    "planned_departure_time" timestamp with time zone,
    "actual_arrival_time" timestamp with time zone,
    "actual_departure_time" timestamp with time zone,
    "is_locked" boolean not null default false,
    "wait_duration_minutes" integer,
    "return_location_type" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."driver_trips" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."trip_legs" ENABLE ROW LEVEL SECURITY;

-- Add foreign key constraints for driver_trips
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'driver_trips_driver_id_fkey'
    ) THEN
        ALTER TABLE "public"."driver_trips" 
        ADD CONSTRAINT "driver_trips_driver_id_fkey" 
        FOREIGN KEY (driver_id) 
        REFERENCES staff(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

-- Add foreign key constraints for trip_legs
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'trip_legs_trip_id_fkey'
    ) THEN
        ALTER TABLE "public"."trip_legs" 
        ADD CONSTRAINT "trip_legs_trip_id_fkey" 
        FOREIGN KEY (trip_id) 
        REFERENCES driver_trips(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'trip_legs_staff_id_fkey'
    ) THEN
        ALTER TABLE "public"."trip_legs" 
        ADD CONSTRAINT "trip_legs_staff_id_fkey" 
        FOREIGN KEY (staff_id) 
        REFERENCES staff(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'trip_legs_appointment_id_fkey'
    ) THEN
        ALTER TABLE "public"."trip_legs" 
        ADD CONSTRAINT "trip_legs_appointment_id_fkey" 
        FOREIGN KEY (appointment_id) 
        REFERENCES appointments(id) 
        ON UPDATE CASCADE 
        ON DELETE SET NULL;
    END IF;
END $$;

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS "driver_trips_trip_date_idx" ON "public"."driver_trips" ("trip_date");
CREATE INDEX IF NOT EXISTS "driver_trips_driver_id_idx" ON "public"."driver_trips" ("driver_id");
CREATE INDEX IF NOT EXISTS "driver_trips_status_idx" ON "public"."driver_trips" ("status");
CREATE INDEX IF NOT EXISTS "trip_legs_trip_id_idx" ON "public"."trip_legs" ("trip_id");
CREATE INDEX IF NOT EXISTS "trip_legs_leg_order_idx" ON "public"."trip_legs" ("trip_id", "leg_order");
CREATE INDEX IF NOT EXISTS "trip_legs_appointment_id_idx" ON "public"."trip_legs" ("appointment_id");

-- Add check constraints for valid values
ALTER TABLE "public"."driver_trips" 
ADD CONSTRAINT "driver_trips_status_check" 
CHECK (status IN ('draft', 'published', 'completed'));

ALTER TABLE "public"."trip_legs" 
ADD CONSTRAINT "trip_legs_leg_type_check" 
CHECK (leg_type IN ('pickup_staff', 'drop_staff', 'appointment', 'wait', 'return'));

ALTER TABLE "public"."trip_legs" 
ADD CONSTRAINT "trip_legs_location_type_check" 
CHECK (location_type IN ('office', 'home', 'metro', 'patient'));

-- Create policies for driver_trips
CREATE POLICY "Enable read access for authenticated users"
ON "public"."driver_trips"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."driver_trips"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."driver_trips"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."driver_trips"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Create policies for trip_legs
CREATE POLICY "Enable read access for authenticated users"
ON "public"."trip_legs"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON "public"."trip_legs"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON "public"."trip_legs"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON "public"."trip_legs"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."driver_trips" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."driver_trips" TO "service_role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."trip_legs" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."trip_legs" TO "service_role";

-- Add trigger to update updated_at timestamp for driver_trips
CREATE TRIGGER update_driver_trips_updated_at BEFORE UPDATE ON "public"."driver_trips"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add trigger to update updated_at timestamp for trip_legs
CREATE TRIGGER update_trip_legs_updated_at BEFORE UPDATE ON "public"."trip_legs"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

