-- ============================================
-- Create Bug Reports Table Migration
-- ============================================

-- Create bug_reports table
CREATE TABLE IF NOT EXISTS "public"."bug_reports" (
    "id" bigint generated by default as identity not null,
    "reported_by" bigint not null,
    "title" text not null,
    "description" text not null,
    "steps_to_reproduce" text,
    "screenshot_urls" text[],
    "status" text not null default 'open',
    "priority" text not null default 'medium',
    "browser_info" text,
    "device_info" text,
    "url" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."bug_reports" ENABLE ROW LEVEL SECURITY;

-- Add foreign key constraint for reported_by
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'bug_reports_reported_by_fkey'
    ) THEN
        ALTER TABLE "public"."bug_reports" 
        ADD CONSTRAINT "bug_reports_reported_by_fkey" 
        FOREIGN KEY (reported_by) 
        REFERENCES sales(id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE;
    END IF;
END $$;

-- Create index on status for filtering
CREATE INDEX IF NOT EXISTS "bug_reports_status_idx" ON "public"."bug_reports"("status");
CREATE INDEX IF NOT EXISTS "bug_reports_reported_by_idx" ON "public"."bug_reports"("reported_by");
CREATE INDEX IF NOT EXISTS "bug_reports_created_at_idx" ON "public"."bug_reports"("created_at");

-- RLS Policies
-- Users can create bug reports
CREATE POLICY "Users can create bug reports"
    ON "public"."bug_reports"
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Users can view their own bug reports
CREATE POLICY "Users can view their own bug reports"
    ON "public"."bug_reports"
    FOR SELECT
    TO authenticated
    USING (auth.uid() = (SELECT user_id FROM sales WHERE id = reported_by LIMIT 1));

-- Users can update their own bug reports (only if status is 'open')
CREATE POLICY "Users can update their own open bug reports"
    ON "public"."bug_reports"
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = (SELECT user_id FROM sales WHERE id = reported_by LIMIT 1)
        AND status = 'open'
    );

-- Add comment to document the table
COMMENT ON TABLE "public"."bug_reports" IS 'Stores bug reports submitted by users with screenshots and reproduction steps';

